import fs from 'fs-extra';
import path from 'path';
import { toNpmPackageName } from '../utils/packageName.js';
import { mergeFeatureServerDependencies } from '../core/featureRegistry.js';
import {
  flattenConfigFeatures,
  hasScaffoldFeature,
  isCliLayout,
  useTypeScript,
} from '../config/userConfig.js';
import {
  clientAuthStub,
  serverAuthMiddleware,
  serverAuthRoutes,
} from '../features/auth/scaffold.js';
import {
  serverDbModule,
  serverDbRoutes,
  sharedDbReadme,
} from '../features/database/scaffold.js';
import {
  serverLoggerModule,
  sharedLoggerModule,
} from '../features/logging/scaffold.js';

/**
 * @param {import('../config/userConfig.js').UserConfig} config
 */
function serverDependencies(config) {
  /** @type {Record<string, string>} */
  const d = {
    express: '^4.21.2',
    cors: '^2.8.5',
    dotenv: '^16.4.7',
  };
  Object.assign(d, mergeFeatureServerDependencies(config));
  return d;
}

/**
 * @param {import('../config/userConfig.js').UserConfig} config
 * @param {string} scope
 */
function buildRootPackageJson(config, scope) {
  const workspaces = ['shared'];
  if (config.stack.frontend === 'react-vite') workspaces.push('client');
  if (config.stack.backend === 'node-express') workspaces.push('server');

  /** @type {Record<string, string>} */
  const scripts = {};
  const devParts = [];

  if (config.stack.backend === 'node-express') {
    scripts['dev:server'] = 'npm run dev --workspace=server';
    devParts.push('"npm run dev:server"');
  }
  if (config.stack.frontend === 'react-vite') {
    scripts['dev:client'] = 'npm run dev --workspace=client';
    devParts.push('"npm run dev:client"');
  }
  if (devParts.length > 1) {
    scripts.dev = `concurrently ${devParts.join(' ')}`;
  } else if (devParts.length === 1) {
    scripts.dev = devParts[0].replaceAll('"', '');
  }

  if (config.stack.backend === 'node-express') {
    scripts.start = 'npm run start --workspace=server';
  }

  /** @type {Record<string, string>} */
  const devDependencies = {};
  if (devParts.length > 1) {
    devDependencies.concurrently = '^9.1.2';
  }

  /** @type {Record<string, unknown>} */
  const pkg = {
    name: scope,
    version: '1.0.0',
    private: true,
    type: 'module',
    description: `Generated by tejasetup — ${config.projectName}`,
    workspaces,
    scripts,
  };

  if (Object.keys(devDependencies).length) {
    pkg.devDependencies = devDependencies;
  }

  if (isCliLayout(config) && config.stack.cli === 'node') {
    pkg.bin = { [scope]: './bin/cli.js' };
    pkg.dependencies = { commander: '^13.1.0' };
    if (!pkg.scripts.start) pkg.scripts.start = `node bin/cli.js`;
  }

  return pkg;
}

function gitignoreContent() {
  return `node_modules/
dist/
build/
.env.local
.DS_Store
*.log
logs/*.log
data/*.db
.cache/
`;
}

/**
 * @param {import('../config/userConfig.js').UserConfig} config
 */
function dotenvContent(config) {
  const lines = [
    `PROJECT_NAME=${config.projectName}`,
    `PORT=3001`,
    `VITE_APP_NAME=${config.projectName}`,
    `JWT_SECRET=change-me-in-production`,
    `SQLITE_PATH=./data/app.db`,
    `# DATABASE_URL=postgres://user:pass@localhost:5432/db`,
    ``,
    `# Features: ${flattenConfigFeatures(config).join(', ') || 'none'}`,
  ];
  return lines.join('\n');
}

/**
 * @param {import('../config/userConfig.js').UserConfig} config
 */
function readmeContent(config) {
  const stack = [];
  if (config.stack.frontend) stack.push(`- Frontend: ${config.stack.frontend}`);
  if (config.stack.backend) stack.push(`- Backend: ${config.stack.backend}`);
  if (config.stack.cli) stack.push(`- CLI: ${config.stack.cli}`);

  return `# ${config.projectName}

Generated with **tejasetup**.

## Stack

${stack.join('\n') || '- Custom'}

## Scripts

\`\`\`bash
npm install
${isCliLayout(config) && config.stack.cli ? 'npm start    # or: node bin/cli.js hello\n' : 'npm run dev\n'}
\`\`\`

## Layout

- \`shared/\` — shared constants
${config.stack.frontend === 'react-vite' ? '- `client/` — Vite + React\n' : ''}${config.stack.backend === 'node-express' ? '- `server/` — Express API\n' : ''}${isCliLayout(config) && config.stack.cli ? '- `bin/cli.js` — CLI entry\n' : ''}
`;
}

/**
 * @param {import('../config/userConfig.js').UserConfig} config
 */
export function renderServerEntry(config) {
  const imports = [
    `import 'dotenv/config';`,
    `import express from 'express';`,
    `import cors from 'cors';`,
    `import { healthRouter } from './routes/health.js';`,
  ];
  if (hasScaffoldFeature(config, 'auth')) {
    imports.push(`import { authRouter } from './routes/auth.js';`);
  }
  if (hasScaffoldFeature(config, 'database')) {
    imports.push(`import { dbRouter } from './routes/db.js';`);
  }
  if (hasScaffoldFeature(config, 'logging')) {
    imports.push(`import { logger } from './lib/logger.js';`);
  }

  const body = [
    `const app = express();`,
    `app.use(cors({ origin: true }));`,
    `app.use(express.json());`,
  ];

  if (hasScaffoldFeature(config, 'logging')) {
    body.push(
      `app.use((req, _res, next) => { void logger.info(\`\${req.method} \${req.url}\`, { project: process.env.PROJECT_NAME }); next(); });`,
    );
  }

  body.push(`app.use('/api', healthRouter);`);
  if (hasScaffoldFeature(config, 'auth')) {
    body.push(`app.use('/api/auth', authRouter);`);
  }
  if (hasScaffoldFeature(config, 'database')) {
    body.push(`app.use('/api/db', dbRouter);`);
  }

  body.push(`const port = Number(process.env.PORT) || 3001;`);
  body.push(
    `app.listen(port, () => { console.log(\`[${config.projectName}] API http://localhost:\${port}\`); });`,
  );

  return `${imports.join('\n')}\n\n${body.join('\n')}\n`;
}

function healthRouteContent() {
  return `import { Router } from 'express';

export const healthRouter = Router();

healthRouter.get('/health', (_req, res) => {
  res.json({
    ok: true,
    project: process.env.PROJECT_NAME,
    time: new Date().toISOString(),
  });
});
`;
}

/**
 * @param {Map<string, string>} map
 * @param {import('../config/userConfig.js').UserConfig} config
 */
function assignGeneratedFeatureFiles(map, config) {
  const authClientFile = useTypeScript(config)
    ? 'client/src/lib/auth.ts'
    : 'client/src/lib/auth.js';
  if (hasScaffoldFeature(config, 'auth')) {
    if (config.stack.backend === 'node-express') {
      map.set('server/src/middleware/jwt.js', serverAuthMiddleware());
      map.set('server/src/routes/auth.js', serverAuthRoutes(config));
    }
    if (config.stack.frontend === 'react-vite') {
      map.set(authClientFile, clientAuthStub());
    }
  }
  if (hasScaffoldFeature(config, 'database')) {
    if (config.stack.backend === 'node-express') {
      map.set('server/src/db/index.js', serverDbModule(config));
      map.set('server/src/routes/db.js', serverDbRoutes());
    } else {
      map.set('shared/src/db/README.md', sharedDbReadme());
    }
  }
  if (hasScaffoldFeature(config, 'logging')) {
    if (config.stack.backend === 'node-express') {
      map.set('server/src/lib/logger.js', serverLoggerModule());
    } else {
      map.set('shared/src/logger.js', sharedLoggerModule());
    }
  }
}

/**
 * @param {Map<string, string>} map
 * @param {import('../config/userConfig.js').UserConfig} config
 * @param {string} scope
 */
function putShared(map, config, scope) {
  const ts = useTypeScript(config);
  const entry = ts ? './src/index.ts' : './src/index.js';
  map.set(
    'shared/package.json',
    `${JSON.stringify(
      {
        name: `@${scope}/shared`,
        version: '1.0.0',
        private: true,
        type: 'module',
        main: entry,
        exports: { '.': entry },
      },
      null,
      2,
    )}\n`,
  );
  map.set(
    ts ? 'shared/src/index.ts' : 'shared/src/index.js',
    `export const projectName = ${JSON.stringify(config.projectName)};\nexport const features = ${JSON.stringify(config.features)};\n`,
  );
}

/**
 * @param {Map<string, string>} map
 * @param {import('../config/userConfig.js').UserConfig} config
 * @param {string} scope
 */
function putClient(map, config, scope) {
  const proxy =
    config.stack.backend === 'node-express'
      ? `  server: { proxy: { '/api': 'http://localhost:3001' } },\n`
      : '';

  const flat = flattenConfigFeatures(config);
  const featNote =
    flat.length > 0
      ? `Features enabled: ${flat.join(', ')}`
      : 'Add features from tejasetup or extend this page.';

  if (useTypeScript(config)) {
    map.set(
      'client/package.json',
      `${JSON.stringify(
        {
          name: `@${scope}/client`,
          version: '1.0.0',
          private: true,
          type: 'module',
          scripts: {
            dev: 'vite',
            build: 'vite build',
            preview: 'vite preview',
          },
          dependencies: {
            react: '^18.3.1',
            'react-dom': '^18.3.1',
            [`@${scope}/shared`]: '*',
          },
          devDependencies: {
            vite: '^6.0.3',
            '@vitejs/plugin-react': '^4.3.4',
            typescript: '^5.7.3',
            '@types/react': '^18.3.18',
            '@types/react-dom': '^18.3.5',
          },
        },
        null,
        2,
      )}\n`,
    );

    map.set(
      'client/tsconfig.json',
      `${JSON.stringify(
        {
          compilerOptions: {
            target: 'ES2022',
            module: 'ESNext',
            moduleResolution: 'bundler',
            jsx: 'react-jsx',
            strict: true,
            skipLibCheck: true,
            noEmit: true,
            isolatedModules: true,
          },
          include: ['src'],
        },
        null,
        2,
      )}\n`,
    );

    map.set(
      'client/src/vite-env.d.ts',
      `/// <reference types="vite/client" />\n`,
    );

    map.set(
      'client/vite.config.js',
      `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
${proxy}});
`,
    );

    map.set(
      'client/index.html',
      `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${config.projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`,
    );

    map.set(
      'client/src/main.tsx',
      `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
`,
    );

    map.set(
      'client/src/App.tsx',
      `import { projectName } from '@${scope}/shared';
import './App.css';

export default function App() {
  const display = import.meta.env.VITE_APP_NAME || projectName;
  return (
    <main className="app">
      <h1>{display}</h1>
      <p className="lead">React (Vite) + TypeScript</p>
      <p className="meta">${featNote}</p>
    </main>
  );
}
`,
    );
  } else {
    map.set(
      'client/package.json',
      `${JSON.stringify(
        {
          name: `@${scope}/client`,
          version: '1.0.0',
          private: true,
          type: 'module',
          scripts: {
            dev: 'vite',
            build: 'vite build',
            preview: 'vite preview',
          },
          dependencies: {
            react: '^18.3.1',
            'react-dom': '^18.3.1',
            [`@${scope}/shared`]: '*',
          },
          devDependencies: {
            vite: '^6.0.3',
            '@vitejs/plugin-react': '^4.3.4',
          },
        },
        null,
        2,
      )}\n`,
    );

    map.set(
      'client/vite.config.js',
      `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
${proxy}});
`,
    );

    map.set(
      'client/index.html',
      `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${config.projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`,
    );

    map.set(
      'client/src/main.jsx',
      `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
`,
    );

    map.set(
      'client/src/App.jsx',
      `import { projectName } from '@${scope}/shared';
import './App.css';

export default function App() {
  const display = import.meta.env.VITE_APP_NAME || projectName;
  return (
    <main className="app">
      <h1>{display}</h1>
      <p className="lead">React (Vite) starter</p>
      <p className="meta">${featNote}</p>
    </main>
  );
}
`,
    );
  }

  map.set(
    'client/src/App.css',
    `.app {
  max-width: 40rem;
  margin: 4rem auto;
  padding: 0 1.5rem;
  font-family: system-ui, sans-serif;
}
.app h1 {
  font-size: 2rem;
  margin-bottom: 0.5rem;
}
.lead {
  color: #444;
  margin-bottom: 1rem;
}
.meta {
  font-size: 0.9rem;
  color: #666;
}
`,
  );

  map.set(
    'client/src/index.css',
    `* { box-sizing: border-box; }
body {
  margin: 0;
  background: #fafafa;
  color: #111;
}
`,
  );
}

/**
 * @param {Map<string, string>} map
 * @param {import('../config/userConfig.js').UserConfig} config
 * @param {string} scope
 */
function putServerBase(map, config, scope) {
  map.set(
    'server/package.json',
    `${JSON.stringify(
      {
        name: `@${scope}/server`,
        version: '1.0.0',
        private: true,
        type: 'module',
        scripts: {
          dev: 'node --watch src/index.js',
          start: 'node src/index.js',
        },
        dependencies: serverDependencies(config),
      },
      null,
      2,
    )}\n`,
  );
  map.set('server/src/routes/health.js', healthRouteContent());
}

/**
 * @param {Map<string, string>} map
 * @param {import('../config/userConfig.js').UserConfig} config
 */
function putCli(map, config) {
  const name = toNpmPackageName(config.projectName);
  map.set(
    'bin/cli.js',
    `#!/usr/bin/env node
import { program } from 'commander';
import { run } from '../cli/src/index.js';

program
  .name(${JSON.stringify(name)})
  .description(${JSON.stringify(`${config.projectName} CLI`)})
  .version('1.0.0');

program
  .command('hello')
  .description('Sample command')
  .argument('[who]', 'name', 'world')
  .action((who) => {
    run({ who, project: ${JSON.stringify(config.projectName)}, features: ${JSON.stringify(flattenConfigFeatures(config))} });
  });

program.parse();
`,
  );
  map.set(
    'cli/src/index.js',
    `export function run({ who, project, features }) {
  console.log(\`Hello, \${who}! (\${project})\`);
  if (features?.length) console.log('Features:', features.join(', '));
}
`,
  );
}

/**
 * In-memory file tree (single source for write + diff preview).
 * @param {import('../config/userConfig.js').UserConfig} config
 * @returns {Map<string, string>}
 */
export function buildVirtualProjectFiles(config) {
  const map = new Map();
  const scope = toNpmPackageName(config.projectName);

  map.set('.gitignore', gitignoreContent());
  map.set('.env', dotenvContent(config));
  map.set('README.md', readmeContent(config));
  map.set(
    'package.json',
    `${JSON.stringify(buildRootPackageJson(config, scope), null, 2)}\n`,
  );

  putShared(map, config, scope);

  if (config.stack.frontend === 'react-vite') {
    putClient(map, config, scope);
  }

  if (config.stack.backend === 'node-express') {
    putServerBase(map, config, scope);
    assignGeneratedFeatureFiles(map, config);
    map.set('server/src/index.js', renderServerEntry(config));
  } else {
    assignGeneratedFeatureFiles(map, config);
  }

  if (isCliLayout(config) && config.stack.cli === 'node') {
    putCli(map, config);
  }

  map.set(
    '.tejasetup/manifest.json',
    `${JSON.stringify(
      {
        version: 2,
        projectName: config.projectName,
        type: config.type,
        mode: config.mode,
        stack: config.stack,
        features: config.features,
        extras: config.extras,
      },
      null,
      2,
    )}\n`,
  );

  return map;
}

/**
 * Write all generated files (after directories exist).
 * @param {string} projectRoot absolute path
 * @param {import('../config/userConfig.js').UserConfig} config
 */
export async function writeProjectFiles(projectRoot, config) {
  const files = buildVirtualProjectFiles(config);
  for (const [rel, content] of files) {
    const abs = path.join(projectRoot, rel);
    await fs.ensureDir(path.dirname(abs));
    if (rel === 'bin/cli.js') {
      await fs.writeFile(abs, content, { mode: 0o755 });
    } else {
      await fs.writeFile(abs, content, 'utf8');
    }
  }
}

/**
 * Merge feature deps into server/package.json and refresh server entry (e.g. after `add`).
 * @param {string} projectRoot
 * @param {import('../config/userConfig.js').UserConfig} config
 */
export async function syncServerWorkspace(projectRoot, config) {
  if (config.stack.backend !== 'node-express') return;
  const pkgPath = path.join(projectRoot, 'server/package.json');
  if (!(await fs.pathExists(pkgPath))) return;
  const pkg = await fs.readJson(pkgPath);
  pkg.dependencies = {
    ...(pkg.dependencies ?? {}),
    ...serverDependencies(config),
  };
  await fs.writeJson(pkgPath, pkg, { spaces: 2 });
  await fs.writeFile(
    path.join(projectRoot, 'server/src/index.js'),
    renderServerEntry(config),
    'utf8',
  );
}

/**
 * @param {string} projectRoot
 * @param {import('../config/userConfig.js').UserConfig} config
 * @param {string} scope
 */
export async function updateSharedMetadata(projectRoot, config, scope) {
  const ts = useTypeScript(config);
  const entry = ts ? './src/index.ts' : './src/index.js';
  const indexFile = ts ? 'shared/src/index.ts' : 'shared/src/index.js';
  await fs.writeFile(
    path.join(projectRoot, indexFile),
    `export const projectName = ${JSON.stringify(config.projectName)};\nexport const features = ${JSON.stringify(config.features)};\n`,
    'utf8',
  );
  await fs.writeFile(
    path.join(projectRoot, 'shared/package.json'),
    `${JSON.stringify(
      {
        name: `@${scope}/shared`,
        version: '1.0.0',
        private: true,
        type: 'module',
        main: entry,
        exports: { '.': entry },
      },
      null,
      2,
    )}\n`,
    'utf8',
  );
}
